# Generated by Django 2.1.7 on 2019-04-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190402_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice',
            new_name='choice_text',
        ),
    ]
